In [27]:
import pandas as pd
df=pd.read_csv("ecommerce_dataset.csv")
df.head(5)

,order_id,customer_id,order_date,product_category,product_name,sales,quantity,region
0,1001,302,2023-01-01,Electronics,Item_B,2655.08,1,West
1,1002,379,2023-01-02,Home,Item_C,411.84,2,East
2,1003,292,2023-01-03,Groceries,Item_B,4173.73,2,South
3,1004,214,2023-01-04,Clothing,Item_B,3034.99,3,East
4,1005,306,2023-01-05,Electronics,Item_B,663.17,6,South

In [28]:
df.shape

(1000, 8)

In [29]:
df.isnull().sum()

order_id            0
customer_id         0
order_date          0
product_category    0
product_name        0
sales               0
quantity            0
region              0
dtype: int64

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1000 non-null   int64
 1   customer_id       1000 non-null   int64
 2   order_date        1000 non-null   object
 3   product_category  1000 non-null   object
 4   product_name      1000 non-null   object
 5   sales             1000 non-null   float64
 6   quantity          1000 non-null   int64
 7   region            1000 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 62.6+ KB

In [31]:
df["order_date"]=pd.to_datetime(df["order_date"])

In [32]:
df.columns

Index(['order_id', 'customer_id', 'order_date', 'product_category',
       'product_name', 'sales', 'quantity', 'region'],
      dtype='object')

In [33]:
df["month"]=df["order_date"].dt.month

In [50]:
df["year"]=df["order_date"].dt.year
df["day"]=df["order_date"].dt.day
df["qurter"]=df["order_date"].dt.quarter

In [51]:
df.duplicated().sum()

np.int64(0)

In [52]:
df.drop_duplicates(inplace=True)

In [53]:
df["sales"]=df["sales"].astype(int)

In [54]:
df.head(3)

,order_id,customer_id,order_date,product_category,product_name,sales,quantity,region,month,year,day,qurter
0,1001,302,2023-01-01,Electronics,Item_B,2655,1,west,1,2023,1,1
1,1002,379,2023-01-02,Home,Item_C,411,2,east,1,2023,2,1
2,1003,292,2023-01-03,Groceries,Item_B,4173,2,south,1,2023,3,1

In [55]:
df["region"].unique()

array(['west', 'east', 'south', 'north'], dtype=object)

In [56]:
df["region"]=df["region"].str.lower()

In [57]:
df.describe(include="all")

,order_id,customer_id,order_date,product_category,product_name,sales,quantity,region,month,year,day,qurter
count,1000.000000,1000.000000,1000,1000,1000,1000.000000,1000.000000,1000,1000.000000,1000.000000,1000.000000,1000.000000
unique,NaN,NaN,NaN,5,5,NaN,NaN,4,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,Beauty,Item_D,NaN,NaN,east,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,206,223,NaN,NaN,279,NaN,NaN,NaN,NaN
mean,1500.500000,300.697000,2024-05-14 12:00:00,NaN,NaN,2519.255000,5.022000,NaN,6.100000,2023.904000,15.672000,2.369000
min,1001.000000,200.000000,2023-01-01 00:00:00,NaN,NaN,100.000000,1.000000,NaN,1.000000,2023.000000,1.000000,1.000000
25%,1250.750000,250.750000,2023-09-07 18:00:00,NaN,NaN,1369.250000,3.000000,NaN,3.000000,2023.000000,8.000000,1.000000
50%,1500.500000,303.000000,2024-05-14 12:00:00,NaN,NaN,2513.500000,5.000000,NaN,6.000000,2024.000000,16.000000,2.000000
75%,1750.250000,349.250000,2025-01-19 06:00:00,NaN,NaN,3710.500000,7.000000,NaN,9.000000,2025.000000,23.000000,3.000000
max,2000.000000,399.000000,2025-09-26 00:00:00,NaN,NaN,4989.000000,9.000000,NaN,12.000000,2025.000000,31.000000,4.000000
std,288.819436,57.629249,NaN,NaN,NaN,1411.242505,2.545584,NaN,3.307407,0.790828,8.780861,1.069571

In [66]:
from sqlalchemy import create_engine
v=create_engine("mssql+pyodbc://@localhost\\SQLEXPRESS/MyDatabase?driver=ODBC+Driver+17+for+SQL+Server&Trusted_connection=yes"
               )
df.to_sql("man",v,if_exists="replace",index=False)

C:\Users\hp\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

130